CREATE SEQUENCE user_seq
    START WITH 1000  
    INCREMENT BY 50;	   

CREATE SEQUENCE project_seq 
    START WITH 1000  
    INCREMENT BY 50;	   
    
CREATE SEQUENCE person_seq 
    START WITH 1000  
    INCREMENT BY 50;	   
    