- changeSet:
    id: 1.0/7
    author: elad
    comment: ""
    changes:
     - insert:
         tableName: Users
         columns:
         - column:
             name: id
             value: 1
         - column:
             name: login
             value: system
         - column:
             name: password_hash
             value: "$2a$10$mE.qmcV0mFU5NcKh73TZx.z4ueI/.bDWbj0T1BYyqP481kGGarKLG"
     	 - column:
             name: first_name
             value: "System"
         - column:
             name: last_name
             value: "System"
         - column:
             name: email
             value: "system@localhost"
 		 - column:
             name: image_url
             value:
     	 - column:
             name: activated
             value: true
         - column:
             name: lang_key
             value: "en"
         - column:
             name: created_by
             value: system
 		 - column:
             name: last_modified_by
             value: system